Err(
    consumed=24,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[5:17 len=6] Token,
    next_token=[6:7 len=4] Token,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "kwif",
            Path_Cons(
              "missing",
              Path_Cons(
                "condition",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "if_missing_condition",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Null,
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
