Err(
    consumed=39,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[5:14 len=6] Token,
    next_token=[6:6 len=2] Token,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "trailing",
            Path_Cons(
              "closure",
              Path_Cons(
                "bad",
                Path_Cons(
                  "attr",
                  Path_End
                )
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "trailing_closure_bad_attr",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "x",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Null,
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
