Err(
    consumed=20,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[4:13 len=2] Token,
    next_token=[5:2 len=1] Token,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "extra",
            Path_Cons(
              "rbrace",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "extra_rbrace",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_Return(
                  Expr_Int(
                    "0"
                  )
                ),
                Stmt_End
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
