Err(
    consumed=39,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[6:6 len=5] Token,
    next_token=[7:5 len=6] Token,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "kwif",
            Path_Cons(
              "kwlet",
              Path_Cons(
                "missing",
                Path_Cons(
                  "expr",
                  Path_End
                )
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "if_let_missing_expr",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "value",
                Type_Path(
                  "Option",
                  Type_Tail_Generic(
                    TypeArg_Cons(
                      Type_Path(
                        "i64",
                        Type_Tail_End
                      ),
                      TypeArg_End
                    )
                  )
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Null,
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
