Err(
    consumed=35,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[4:28 len=1] Token,
    next_token=[4:29 len=2] Token,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "record",
            Path_Cons(
              "update",
              Path_Cons(
                "missing",
                Path_Cons(
                  "pipe",
                  Path_End
                )
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "record_update_missing_pipe",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "base",
                Type_Path(
                  "Point",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "Point",
              Type_Tail_End
            ),
            Expr_Block(
              Null,
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
