Err(
    consumed=31,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[4:13 len=2] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "kwtype",
            Path_Cons(
              "args",
              Path_Cons(
                "leading",
                Path_Cons(
                  "comma",
                  Path_End
                )
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "type_args_leading_comma",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "xs",
                Type_Path(
                  "Result",
                  Type_Tail_Generic(
                    Null
                  )
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_Return(
                  Expr_Int(
                    "0"
                  )
                ),
                Stmt_End
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
