Err(
    consumed=43,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[7:6 len=2] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "pattern",
            Path_Cons(
              "double",
              Path_Cons(
                "bind",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "pattern_double_bind",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "value",
                Type_Path(
                  "Option",
                  Type_Tail_Generic(
                    TypeArg_Cons(
                      Type_Path(
                        "i64",
                        Type_Tail_End
                      ),
                      TypeArg_End
                    )
                  )
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_Expr(
                  Expr_Match(
                    Expr_MatchIdent(
                      "value",
                      MatchIdent_Name
                    ),
                    MatchArm_Cons(
                      MatchArm(
                        Null,
                        MatchGuard_None,
                        Expr_IdentTail(
                          "x",
                          IdentTail_None
                        )
                      ),
                      MatchArm_Cons(
                        MatchArm(
                          Pattern_IdentStart(
                            "_",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          MatchGuard_None,
                          Expr_Int(
                            "0"
                          )
                        ),
                        MatchArm_End
                      )
                    )
                  )
                ),
                Stmt_End
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
