Err(
    consumed=29,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[4:29 len=2] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "pipe",
            Path_Cons(
              "double",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "pipe_double",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "x",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Null,
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
