Err(
    consumed=24,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[4:15 len=2] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "prefix",
            Path_Cons(
              "before",
              Path_Cons(
                "rparen",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "prefix_before_rparen",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_Return(
                  Expr_Paren(
                    Null
                  )
                ),
                Stmt_End
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
