[1:1 len=9] leading=[] KwNamespace trailing=[]
[1:11 len=6] leading=[] Ident("parser") trailing=[]
[1:17 len=1] leading=[] Dot trailing=[]
[1:18 len=5] leading=[] Ident("error") trailing=[]
[1:23 len=1] leading=[] Dot trailing=[]
[1:24 len=6] leading=[] Ident("kwtype") trailing=[]
[1:30 len=1] leading=[] Dot trailing=[]
[1:31 len=7] leading=[] Ident("missing") trailing=[]
[1:38 len=1] leading=[] Dot trailing=[]
[1:39 len=3] leading=[] Ident("rhs") trailing=[]
[1:42 len=2] leading=[] Newline("\n\n") trailing=[]
[3:1 len=4] leading=[] KwType trailing=[]
[3:6 len=6] leading=[] Ident("UserId") trailing=[]
[3:13 len=1] leading=[] Eq trailing=[]
[0:0 len=0] leading=[] Eof trailing=[]
0
