Err(
    consumed=25,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[5:9 len=2] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "kwdata",
            Path_Cons(
              "generic",
              Path_Cons(
                "missing",
                Path_Cons(
                  "rbracket",
                  Path_End
                )
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Adt(
        AdtItem(
          "Option",
          Null,
          AdtVariant_Cons(
            AdtVariant(
              "Some",
              AdtVariantArg_Ident(
                "T",
                AdtVariantArg_Type(
                  Type_Tail_End,
                  TypeArg_End
                )
              )
            ),
            AdtVariant_Cons(
              AdtVariant(
                "None",
                TypeArg_End
              ),
              AdtVariant_End
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
