[1:1 len=9] leading=[] KwNamespace trailing=[]
[1:11 len=6] leading=[] Ident("parser") trailing=[]
[1:17 len=1] leading=[] Dot trailing=[]
[1:18 len=5] leading=[] Ident("error") trailing=[]
[1:23 len=1] leading=[] Dot trailing=[]
[1:24 len=7] leading=[] Ident("kwunion") trailing=[]
[1:31 len=1] leading=[] Dot trailing=[]
[1:32 len=7] leading=[] Ident("missing") trailing=[]
[1:39 len=1] leading=[] Dot trailing=[]
[1:40 len=5] leading=[] Ident("comma") trailing=[]
[1:45 len=2] leading=[] Newline("\n\n") trailing=[]
[3:1 len=5] leading=[] KwUnion trailing=[]
[3:7 len=4] leading=[] Ident("Bits") trailing=[]
[3:12 len=6] leading=[] LBrace trailing=[]
[4:5 len=2] leading=[] Ident("lo") trailing=[]
[4:7 len=1] leading=[] Colon trailing=[]
[4:9 len=3] leading=[] Ident("u32") trailing=[]
[4:12 len=5] leading=[] Newline("\n    ") trailing=[]
[5:5 len=2] leading=[] Ident("hi") trailing=[]
[5:7 len=1] leading=[] Colon trailing=[]
[5:9 len=3] leading=[] Ident("u32") trailing=[]
[5:12 len=2] leading=[] Comma trailing=[]
[6:1 len=1] leading=[] RBrace trailing=[]
[0:0 len=0] leading=[] Eof trailing=[]
0
