Err(
    consumed=54,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[7:13 len=2] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "kwasm",
            Path_Cons(
              "input",
              Path_Cons(
                "missing",
                Path_Cons(
                  "reg",
                  Path_End
                )
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "bad_asm_input",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "ptr",
                Type_Path(
                  "Ptr",
                  Type_Tail_Generic(
                    TypeArg_Cons(
                      Type_Path(
                        "u8",
                        Type_Tail_End
                      ),
                      TypeArg_End
                    )
                  )
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Unsafe(
              Expr_Block(
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "v",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Asm(
                      Null,
                      AsmOutput_Cons(
                        "rax",
                        AsmOutput_End
                      ),
                      AsmString_Cons(
                        Expr_String,
                        AsmString_End
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_Return(
                      Expr_IdentTail(
                        "v",
                        IdentTail_None
                      )
                    ),
                    Stmt_End
                  )
                ),
                TailExpr_None
              )
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
