[1:1 len=9] leading=[] KwNamespace trailing=[]
[1:11 len=6] leading=[] Ident("parser") trailing=[]
[1:17 len=1] leading=[] Dot trailing=[]
[1:18 len=5] leading=[] Ident("error") trailing=[]
[1:23 len=1] leading=[] Dot trailing=[]
[1:24 len=7] leading=[] Ident("kwreset") trailing=[]
[1:31 len=1] leading=[] Dot trailing=[]
[1:32 len=3] leading=[] Ident("bad") trailing=[]
[1:35 len=1] leading=[] Dot trailing=[]
[1:36 len=5] leading=[] Ident("label") trailing=[]
[1:41 len=1] leading=[] Dot trailing=[]
[1:42 len=8] leading=[] Ident("position") trailing=[]
[1:50 len=2] leading=[] Newline("\n\n") trailing=[]
[3:1 len=3] leading=[] KwDef trailing=[]
[3:5 len=15] leading=[] Ident("reset_bad_label") trailing=[]
[3:20 len=1] leading=[] LParen trailing=[]
[3:21 len=1] leading=[] RParen trailing=[]
[3:22 len=1] leading=[] Colon trailing=[]
[3:24 len=3] leading=[] Ident("i64") trailing=[]
[3:28 len=1] leading=[] Eq trailing=[]
[3:30 len=6] leading=[] LBrace trailing=[]
[4:5 len=3] leading=[] KwLet trailing=[]
[4:9 len=5] leading=[] Ident("value") trailing=[]
[4:15 len=1] leading=[] Eq trailing=[]
[4:17 len=5] leading=[] KwReset trailing=[]
[4:23 len=1] leading=[] LBrace trailing=[]
[4:25 len=6] leading=[] Atom("parse") trailing=[]
[4:31 len=9] leading=[] Newline("\n        ") trailing=[]
[5:9 len=1] leading=[] IntLit("1") trailing=[]
[5:10 len=6] leading=[] RBrace trailing=[]
[6:6 len=5] leading=[] Newline("\n    ") trailing=[]
[7:5 len=6] leading=[] KwReturn trailing=[]
[7:12 len=5] leading=[] Ident("value") trailing=[]
[7:17 len=2] leading=[] RBrace trailing=[]
[0:0 len=0] leading=[] Eof trailing=[]
0
