Err(
    consumed=29,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[6:6 len=5] Token,
    next_token=[7:5 len=6] Token,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "kwcontinue",
            Path_Cons(
              "label",
              Path_Cons(
                "no",
                Path_Cons(
                  "colon",
                  Path_End
                )
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "continue_label_no_colon",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Null,
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
