Err(
    consumed=32,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[5:13 len=2] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "record",
            Path_Cons(
              "double",
              Path_Cons(
                "colon",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "record_double_colon",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "value",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Record(
                    Null
                  )
                ),
                Stmt_Cons(
                  Stmt_Return(
                    Expr_Int(
                      "0"
                    )
                  ),
                  Stmt_End
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
