OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "comments",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "keep_comments",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i32",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "value",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Int(
                    "1"
                  )
                ),
                Stmt_Cons(
                  Stmt_Return(
                    Expr_IdentTail(
                      "value",
                      IdentTail_None
                    )
                  ),
                  Stmt_End
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
