OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "attrs",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "entry",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i32",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_Return(
                  Expr_Int(
                    "0"
                  )
                ),
                Stmt_End
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
