OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "literals",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "numbers_and_names",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "dec",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Int(
                    "123_456"
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "hex",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Int(
                      "0xCAFE_babe"
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "oct",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_Int(
                        "0o755"
                      )
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "bin",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_Int(
                          "0b1010_0101"
                        )
                      ),
                      Stmt_Cons(
                        Stmt_LetPatternTyped(
                          Pattern_IdentStart(
                            "float_a",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          Type_Path(
                            "",
                            Type_Tail_End
                          ),
                          Expr_Float(
                            "1.25"
                          )
                        ),
                        Stmt_Cons(
                          Stmt_LetPatternTyped(
                            Pattern_IdentStart(
                              "float_b",
                              PatternAfterIdent_Atom(
                                PatternIdent_Name
                              )
                            ),
                            Type_Path(
                              "",
                              Type_Tail_End
                            ),
                            Expr_Float(
                              "6.02e23"
                            )
                          ),
                          Stmt_Cons(
                            Stmt_LetPatternTyped(
                              Pattern_IdentStart(
                                "float_c",
                                PatternAfterIdent_Atom(
                                  PatternIdent_Name
                                )
                              ),
                              Type_Path(
                                "",
                                Type_Tail_End
                              ),
                              Expr_Float(
                                "3.14f32"
                              )
                            ),
                            Stmt_Cons(
                              Stmt_LetPatternTyped(
                                Pattern_IdentStart(
                                  "int_suffix",
                                  PatternAfterIdent_Atom(
                                    PatternIdent_Name
                                  )
                                ),
                                Type_Path(
                                  "",
                                  Type_Tail_End
                                ),
                                Expr_Int(
                                  "99usize"
                                )
                              ),
                              Stmt_Cons(
                                Stmt_LetPatternTyped(
                                  Pattern_IdentStart(
                                    "ok",
                                    PatternAfterIdent_Atom(
                                      PatternIdent_Name
                                    )
                                  ),
                                  Type_Path(
                                    "",
                                    Type_Tail_End
                                  ),
                                  Expr_Bool(
                                    1
                                  )
                                ),
                                Stmt_Cons(
                                  Stmt_LetPatternTyped(
                                    Pattern_IdentStart(
                                      "no",
                                      PatternAfterIdent_Atom(
                                        PatternIdent_Name
                                      )
                                    ),
                                    Type_Path(
                                      "",
                                      Type_Tail_End
                                    ),
                                    Expr_Bool(
                                      0
                                    )
                                  ),
                                  Stmt_Cons(
                                    Stmt_LetPatternTyped(
                                      Pattern_IdentStart(
                                        "atom",
                                        PatternAfterIdent_Atom(
                                          PatternIdent_Name
                                        )
                                      ),
                                      Type_Path(
                                        "",
                                        Type_Tail_End
                                      ),
                                      Expr_Atom(
                                        "ok"
                                      )
                                    ),
                                    Stmt_Cons(
                                      Stmt_LetPatternTyped(
                                        Pattern_IdentStart(
                                          "unicode",
                                          PatternAfterIdent_Atom(
                                            PatternIdent_Name
                                          )
                                        ),
                                        Type_Path(
                                          "",
                                          Type_Tail_End
                                        ),
                                        Expr_IdentTail(
                                          "测试一下语法容忍度",
                                          IdentTail_None
                                        )
                                      ),
                                      Stmt_Cons(
                                        Stmt_LetPatternTyped(
                                          Pattern_IdentStart(
                                            "emoji",
                                            PatternAfterIdent_Atom(
                                              PatternIdent_Name
                                            )
                                          ),
                                          Type_Path(
                                            "",
                                            Type_Tail_End
                                          ),
                                          Expr_IdentTail(
                                            "🍋",
                                            IdentTail_None
                                          )
                                        ),
                                        Stmt_Cons(
                                          Stmt_Return(
                                            Expr_IdentTail(
                                              "dec",
                                              IdentTail_None
                                            )
                                          ),
                                          Stmt_End
                                        )
                                      )
                                    )
                                  )
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
