OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "strings",
            Path_Cons(
              "basic",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "strings",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i32",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "plain",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_String
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "escaped",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_String
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "c_text",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_String
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "raw_one",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_String
                      ),
                      Stmt_Cons(
                        Stmt_LetPatternTyped(
                          Pattern_IdentStart(
                            "raw_hash",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          Type_Path(
                            "",
                            Type_Tail_End
                          ),
                          Expr_String
                        ),
                        Stmt_Cons(
                          Stmt_LetPatternTyped(
                            Pattern_IdentStart(
                              "trick",
                              PatternAfterIdent_Atom(
                                PatternIdent_Name
                              )
                            ),
                            Type_Path(
                              "",
                              Type_Tail_End
                            ),
                            Expr_String
                          ),
                          Stmt_Cons(
                            Stmt_LetPatternTyped(
                              Pattern_IdentStart(
                                "prefixed",
                                PatternAfterIdent_Atom(
                                  PatternIdent_Name
                                )
                              ),
                              Type_Path(
                                "",
                                Type_Tail_End
                              ),
                              Expr_String
                            ),
                            Stmt_Cons(
                              Stmt_LetPatternTyped(
                                Pattern_IdentStart(
                                  "prefixed_raw",
                                  PatternAfterIdent_Atom(
                                    PatternIdent_Name
                                  )
                                ),
                                Type_Path(
                                  "",
                                  Type_Tail_End
                                ),
                                Expr_String
                              ),
                              Stmt_Cons(
                                Stmt_Return(
                                  Expr_Int(
                                    "0"
                                  )
                                ),
                                Stmt_End
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
