OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "strings",
            Path_Cons(
              "multiline",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "multiline",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "name",
                Type_Path(
                  "String",
                  Type_Tail_End
                )
              ),
              Param_Cons(
                Param(
                  "id",
                  Type_Path(
                    "i64",
                    Type_Tail_End
                  )
                ),
                Param_End
              )
            ),
            Type_Path(
              "String",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "normal",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_String
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "delimited",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_String
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "raw_multi",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_String
                    ),
                    Stmt_Cons(
                      Stmt_Return(
                        Expr_IdentTail(
                          "normal",
                          IdentTail_None
                        )
                      ),
                      Stmt_End
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
