OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "operators",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "operators",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "a",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_Cons(
                Param(
                  "b",
                  Type_Path(
                    "i64",
                    Type_Tail_End
                  )
                ),
                Param_Cons(
                  Param(
                    "flags",
                    Type_Path(
                      "i64",
                      Type_Tail_End
                    )
                  ),
                  Param_End
                )
              )
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "arithmetic",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Binary(
                    OpSub,
                    Expr_Binary(
                      OpAdd,
                      Expr_IdentTail(
                        "a",
                        IdentTail_None
                      ),
                      Expr_IdentTail(
                        "b",
                        IdentTail_None
                      )
                    ),
                    Expr_Binary(
                      OpMod,
                      Expr_Binary(
                        OpDiv,
                        Expr_Binary(
                          OpMul,
                          Expr_IdentTail(
                            "a",
                            IdentTail_None
                          ),
                          Expr_IdentTail(
                            "b",
                            IdentTail_None
                          )
                        ),
                        Expr_Int(
                          "2"
                        )
                      ),
                      Expr_Int(
                        "3"
                      )
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "compare",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Binary(
                      OpOr,
                      Expr_Binary(
                        OpEqEq,
                        Expr_IdentTail(
                          "a",
                          IdentTail_None
                        ),
                        Expr_IdentTail(
                          "b",
                          IdentTail_None
                        )
                      ),
                      Expr_Binary(
                        OpAnd,
                        Expr_Binary(
                          OpAnd,
                          Expr_Binary(
                            OpAnd,
                            Expr_Binary(
                              OpAnd,
                              Expr_Binary(
                                OpBangEq,
                                Expr_IdentTail(
                                  "a",
                                  IdentTail_None
                                ),
                                Expr_IdentTail(
                                  "b",
                                  IdentTail_None
                                )
                              ),
                              Expr_Binary(
                                OpLtEq,
                                Expr_IdentTail(
                                  "a",
                                  IdentTail_None
                                ),
                                Expr_IdentTail(
                                  "b",
                                  IdentTail_None
                                )
                              )
                            ),
                            Expr_Binary(
                              OpGtEq,
                              Expr_IdentTail(
                                "a",
                                IdentTail_None
                              ),
                              Expr_IdentTail(
                                "b",
                                IdentTail_None
                              )
                            )
                          ),
                          Expr_Binary(
                            OpLt,
                            Expr_IdentTail(
                              "a",
                              IdentTail_None
                            ),
                            Expr_IdentTail(
                              "b",
                              IdentTail_None
                            )
                          )
                        ),
                        Expr_Binary(
                          OpGt,
                          Expr_IdentTail(
                            "a",
                            IdentTail_None
                          ),
                          Expr_IdentTail(
                            "b",
                            IdentTail_None
                          )
                        )
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "bits",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_Binary(
                        OpBitOr,
                        Expr_ParenIdent(
                          "flags",
                          ParenIdent_Binary(
                            OpBitAnd,
                            Expr_Int(
                              "0xff"
                            )
                          )
                        ),
                        Expr_Binary(
                          OpBitXor,
                          Expr_Int(
                            "0b10"
                          ),
                          Expr_Binary(
                            OpShr,
                            Expr_Paren(
                              ExprList_Cons(
                                Expr_Binary(
                                  OpShl,
                                  Expr_Int(
                                    "1"
                                  ),
                                  Expr_Int(
                                    "3"
                                  )
                                ),
                                ExprList_End
                              )
                            ),
                            Expr_Int(
                              "1"
                            )
                          )
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "unary",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_Binary(
                          OpAdd,
                          Expr_Prefix(
                            Prefix_Neg,
                            Expr_IdentTail(
                              "a",
                              IdentTail_None
                            )
                          ),
                          Expr_Cast(
                            Expr_Prefix(
                              Prefix_Not,
                              Expr_IdentTail(
                                "compare",
                                IdentTail_None
                              )
                            ),
                            Type_Path(
                              "i64",
                              Type_Tail_End
                            )
                          )
                        )
                      ),
                      Stmt_Cons(
                        Stmt_LetPatternTyped(
                          Pattern_IdentStart(
                            "ptr_value",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          Type_Path(
                            "",
                            Type_Tail_End
                          ),
                          Expr_Deref(
                            Expr_IdentTail(
                              "ptr",
                              IdentTail_None
                            )
                          )
                        ),
                        Stmt_Cons(
                          Stmt_Expr(
                            Expr_Assign(
                              Expr_IdentTail(
                                "cell",
                                IdentTail_None
                              ),
                              Expr_Assign(
                                Expr_IdentTail(
                                  "a",
                                  IdentTail_None
                                ),
                                Expr_IdentTail(
                                  "b",
                                  IdentTail_None
                                )
                              )
                            )
                          ),
                          Stmt_Cons(
                            Stmt_Return(
                              Expr_Binary(
                                OpPipeGt,
                                Expr_Binary(
                                  OpPipeGt,
                                  Expr_IdentTail(
                                    "arithmetic",
                                    IdentTail_None
                                  ),
                                  Expr_IdentTail(
                                    "step",
                                    IdentTail_Call(
                                      Arg_Cons(
                                        Expr_IdentTail(
                                          "_",
                                          IdentTail_None
                                        ),
                                        Arg_End
                                      ),
                                      IdentCallClosure_None
                                    )
                                  )
                                ),
                                Expr_IdentTail(
                                  "finish",
                                  IdentTail_Call(
                                    Arg_End,
                                    IdentCallClosure_None
                                  )
                                )
                              )
                            ),
                            Stmt_End
                          )
                        )
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
