OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "statement",
            Path_Cons(
              "boundaries",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "statement_boundaries",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i32",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "a",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Int(
                    "1"
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "b",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Int(
                      "2"
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "c",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_Int(
                        "3"
                      )
                    ),
                    Stmt_Cons(
                      Stmt_Expr(
                        Expr_IdentTail(
                          "call",
                          IdentTail_Call(
                            Arg_Cons(
                              Expr_IdentTail(
                                "a",
                                IdentTail_None
                              ),
                              Arg_End
                            ),
                            IdentCallClosure_Some(
                              Expr_Closure(
                                Param_Cons(
                                  Param(
                                    "x",
                                    Type_Path(
                                      "",
                                      Type_Tail_End
                                    )
                                  ),
                                  Param_End
                                ),
                                Expr_Block(
                                  Stmt_Cons(
                                    Stmt_Expr(
                                      Expr_Binary(
                                        OpAdd,
                                        Expr_IdentTail(
                                          "x",
                                          IdentTail_None
                                        ),
                                        Expr_Int(
                                          "1"
                                        )
                                      )
                                    ),
                                    Stmt_End
                                  ),
                                  TailExpr_None
                                )
                              )
                            )
                          )
                        )
                      ),
                      Stmt_Cons(
                        Stmt_LetPatternTyped(
                          Pattern_IdentStart(
                            "same_line_is_not_separator",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          Type_Path(
                            "",
                            Type_Tail_End
                          ),
                          Expr_Int(
                            "1"
                          )
                        ),
                        Stmt_Cons(
                          Stmt_LetPatternTyped(
                            Pattern_IdentStart(
                              "next_token_same_line",
                              PatternAfterIdent_Atom(
                                PatternIdent_Name
                              )
                            ),
                            Type_Path(
                              "",
                              Type_Tail_End
                            ),
                            Expr_Int(
                              "2"
                            )
                          ),
                          Stmt_Cons(
                            Stmt_Return(
                              Expr_Binary(
                                OpAdd,
                                Expr_Binary(
                                  OpAdd,
                                  Expr_IdentTail(
                                    "a",
                                    IdentTail_None
                                  ),
                                  Expr_IdentTail(
                                    "b",
                                    IdentTail_None
                                  )
                                ),
                                Expr_IdentTail(
                                  "c",
                                  IdentTail_None
                                )
                              )
                            ),
                            Stmt_End
                          )
                        )
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
