OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "layout",
            Path_Cons(
              "continuation",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "continuation_layout",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "value",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "x",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Binary(
                    OpAdd,
                    Expr_IdentTail(
                      "value",
                      IdentTail_None
                    ),
                    Expr_Binary(
                      OpMul,
                      Expr_Int(
                        "1"
                      ),
                      Expr_Int(
                        "2"
                      )
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "y",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Binary(
                      OpPipeGt,
                      Expr_Binary(
                        OpPipeGt,
                        Expr_IdentTail(
                          "value",
                          IdentTail_None
                        ),
                        Expr_IdentTail(
                          "step1",
                          IdentTail_Call(
                            Arg_End,
                            IdentCallClosure_None
                          )
                        )
                      ),
                      Expr_IdentTail(
                        "step2",
                        IdentTail_Call(
                          Arg_Cons(
                            Expr_IdentTail(
                              "_",
                              IdentTail_None
                            ),
                            Arg_End
                          ),
                          IdentCallClosure_None
                        )
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "z",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_If(
                        IfCond_Expr(
                          Expr_IfCondIdent(
                            "value",
                            IfCondIdent_Binary(
                              OpGt,
                              Expr_Int(
                                "0"
                              )
                            )
                          )
                        ),
                        Expr_Block(
                          Stmt_Cons(
                            Stmt_Expr(
                              Expr_IdentTail(
                                "value",
                                IdentTail_None
                              )
                            ),
                            Stmt_End
                          ),
                          TailExpr_None
                        ),
                        Expr_Block(
                          Stmt_Cons(
                            Stmt_Expr(
                              Expr_Int(
                                "0"
                              )
                            ),
                            Stmt_End
                          ),
                          TailExpr_None
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_Return(
                        Expr_Binary(
                          OpAdd,
                          Expr_Binary(
                            OpAdd,
                            Expr_IdentTail(
                              "x",
                              IdentTail_None
                            ),
                            Expr_IdentTail(
                              "y",
                              IdentTail_None
                            )
                          ),
                          Expr_IdentTail(
                            "z",
                            IdentTail_None
                          )
                        )
                      ),
                      Stmt_End
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
