OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "delimiters",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "delimiter_newlines",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i32",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "grouped",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Paren(
                    ExprList_Cons(
                      Expr_Binary(
                        OpAdd,
                        Expr_Int(
                          "1"
                        ),
                        Expr_Int(
                          "2"
                        )
                      ),
                      ExprList_End
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "tuple",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_ParenIdent(
                      "grouped",
                      ParenIdent_Tuple(
                        ExprList_Cons(
                          Expr_Binary(
                            OpAdd,
                            Expr_IdentTail(
                              "grouped",
                              IdentTail_None
                            ),
                            Expr_Int(
                              "1"
                            )
                          ),
                          ExprList_End
                        )
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "slice",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_List(
                        ExprList_Cons(
                          Expr_IdentTail(
                            "grouped",
                            IdentTail_None
                          ),
                          ExprList_Cons(
                            Expr_Binary(
                              OpAdd,
                              Expr_IdentTail(
                                "grouped",
                                IdentTail_None
                              ),
                              Expr_Int(
                                "1"
                              )
                            ),
                            ExprList_End
                          )
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "indexed",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_Index(
                          Expr_IdentTail(
                            "slice",
                            IdentTail_None
                          ),
                          ExprList_Cons(
                            Expr_Int(
                              "0"
                            ),
                            ExprList_End
                          )
                        )
                      ),
                      Stmt_Cons(
                        Stmt_Return(
                          Expr_IdentTail(
                            "indexed",
                            IdentTail_None
                          )
                        ),
                        Stmt_End
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
