OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "trailing",
            Path_Cons(
              "closure",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "trailing_closure",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "xs",
                Type_Path(
                  "Vec",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "Vec",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "mapped",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_IdentTail(
                    "map",
                    IdentTail_Call(
                      Arg_Cons(
                        Expr_IdentTail(
                          "xs",
                          IdentTail_None
                        ),
                        Arg_End
                      ),
                      IdentCallClosure_Some(
                        Expr_Closure(
                          Param_Cons(
                            Param(
                              "x",
                              Type_Path(
                                "",
                                Type_Tail_End
                              )
                            ),
                            Param_End
                          ),
                          Expr_Block(
                            Stmt_Cons(
                              Stmt_Expr(
                                Expr_Binary(
                                  OpAdd,
                                  Expr_IdentTail(
                                    "x",
                                    IdentTail_None
                                  ),
                                  Expr_Int(
                                    "1"
                                  )
                                )
                              ),
                              Stmt_End
                            ),
                            TailExpr_None
                          )
                        )
                      )
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "empty",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_IdentTail(
                      "with_scope",
                      IdentTail_Call(
                        Arg_End,
                        IdentCallClosure_Some(
                          Expr_Closure(
                            Param_End,
                            Expr_Block(
                              Stmt_Cons(
                                Stmt_Expr(
                                  Expr_Int(
                                    "0"
                                  )
                                ),
                                Stmt_End
                              ),
                              TailExpr_None
                            )
                          )
                        )
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "typed",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_IdentTail(
                        "fold",
                        IdentTail_Call(
                          Arg_Cons(
                            Expr_IdentTail(
                              "xs",
                              IdentTail_None
                            ),
                            Arg_Cons(
                              Expr_Int(
                                "0"
                              ),
                              Arg_End
                            )
                          ),
                          IdentCallClosure_Some(
                            Expr_Closure(
                              Param_Cons(
                                Param(
                                  "acc",
                                  Type_Path(
                                    "i64",
                                    Type_Tail_End
                                  )
                                ),
                                Param_Cons(
                                  Param(
                                    "x",
                                    Type_Path(
                                      "i64",
                                      Type_Tail_End
                                    )
                                  ),
                                  Param_End
                                )
                              ),
                              Expr_Block(
                                Stmt_Cons(
                                  Stmt_Expr(
                                    Expr_Binary(
                                      OpAdd,
                                      Expr_IdentTail(
                                        "acc",
                                        IdentTail_None
                                      ),
                                      Expr_IdentTail(
                                        "x",
                                        IdentTail_None
                                      )
                                    )
                                  ),
                                  Stmt_End
                                ),
                                TailExpr_None
                              )
                            )
                          )
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_Return(
                        Expr_IdentTail(
                          "mapped",
                          IdentTail_None
                        )
                      ),
                      Stmt_End
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
