OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "records",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "records",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "base",
                Type_Path(
                  "Point",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "Point",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "x",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Int(
                    "1"
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "y",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Int(
                      "2"
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "literal",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_Record(
                        Record_First(
                          "x",
                          RecordTail_Shorthand(
                            RecordField_Cons(
                              RecordField(
                                "y",
                                Expr_Name(
                                  ""
                                )
                              ),
                              RecordField_Cons(
                                RecordField(
                                  "name",
                                  Expr_String
                                ),
                                RecordField_End
                              )
                            )
                          )
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "multi",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_Record(
                          Record_First(
                            "x",
                            RecordTail_Field(
                              Expr_Int(
                                "1"
                              ),
                              RecordField_Cons(
                                RecordField(
                                  "y",
                                  Expr_Int(
                                    "2"
                                  )
                                ),
                                RecordField_End
                              )
                            )
                          )
                        )
                      ),
                      Stmt_Cons(
                        Stmt_LetPatternTyped(
                          Pattern_IdentStart(
                            "update",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          Type_Path(
                            "",
                            Type_Tail_End
                          ),
                          Expr_Record(
                            Record_First(
                              "base",
                              Record_Update(
                                Expr_Name(
                                  ""
                                ),
                                RecordField_Cons(
                                  RecordField(
                                    "y",
                                    Expr_Int(
                                      "3"
                                    )
                                  ),
                                  RecordField_Cons(
                                    RecordField(
                                      "z",
                                      Expr_Int(
                                        "4"
                                      )
                                    ),
                                    RecordField_End
                                  )
                                )
                              )
                            )
                          )
                        ),
                        Stmt_Cons(
                          Stmt_LetPatternTyped(
                            Pattern_IdentStart(
                              "update_multi",
                              PatternAfterIdent_Atom(
                                PatternIdent_Name
                              )
                            ),
                            Type_Path(
                              "",
                              Type_Tail_End
                            ),
                            Expr_Record(
                              Record_First(
                                "base",
                                Record_Update(
                                  Expr_Name(
                                    ""
                                  ),
                                  RecordField_Cons(
                                    RecordField(
                                      "x",
                                      Expr_Field(
                                        Expr_IdentTail(
                                          "literal",
                                          IdentTail_None
                                        ),
                                        "x"
                                      )
                                    ),
                                    RecordField_Cons(
                                      RecordField(
                                        "y",
                                        Expr_Field(
                                          Expr_IdentTail(
                                            "multi",
                                            IdentTail_None
                                          ),
                                          "y"
                                        )
                                      ),
                                      RecordField_End
                                    )
                                  )
                                )
                              )
                            )
                          ),
                          Stmt_Cons(
                            Stmt_Return(
                              Expr_IdentTail(
                                "update",
                                IdentTail_None
                              )
                            ),
                            Stmt_End
                          )
                        )
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
