OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "tuples",
            Path_Cons(
              "slices",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "tuple_slice_index",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "text",
                Type_Path(
                  "String",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "unit",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Paren(
                    ExprList_End
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "grouped",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Paren(
                      ExprList_Cons(
                        Expr_Int(
                          "1"
                        ),
                        ExprList_End
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "one_tuple",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_Paren(
                        ExprList_Cons(
                          Expr_Int(
                            "1"
                          ),
                          ExprList_End
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "pair",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_Paren(
                          ExprList_Cons(
                            Expr_Int(
                              "1"
                            ),
                            ExprList_Cons(
                              Expr_Int(
                                "2"
                              ),
                              ExprList_End
                            )
                          )
                        )
                      ),
                      Stmt_Cons(
                        Stmt_LetPatternTyped(
                          Pattern_IdentStart(
                            "nested",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          Type_Path(
                            "",
                            Type_Tail_End
                          ),
                          Expr_Paren(
                            ExprList_Cons(
                              Expr_Paren(
                                ExprList_Cons(
                                  Expr_Int(
                                    "1"
                                  ),
                                  ExprList_End
                                )
                              ),
                              ExprList_Cons(
                                Expr_Paren(
                                  ExprList_Cons(
                                    Expr_Int(
                                      "2"
                                    ),
                                    ExprList_Cons(
                                      Expr_Int(
                                        "3"
                                      ),
                                      ExprList_End
                                    )
                                  )
                                ),
                                ExprList_End
                              )
                            )
                          )
                        ),
                        Stmt_Cons(
                          Stmt_LetPatternTyped(
                            Pattern_IdentStart(
                              "bytes",
                              PatternAfterIdent_Atom(
                                PatternIdent_Name
                              )
                            ),
                            Type_Path(
                              "",
                              Type_Tail_End
                            ),
                            Expr_Index(
                              Expr_IdentTail(
                                "text",
                                IdentTail_None
                              ),
                              ExprList_Cons(
                                Expr_Binary(
                                  OpRange,
                                  Expr_Int(
                                    "0"
                                  ),
                                  Expr_Int(
                                    "4"
                                  )
                                ),
                                ExprList_End
                              )
                            )
                          ),
                          Stmt_Cons(
                            Stmt_LetPatternTyped(
                              Pattern_IdentStart(
                                "cp",
                                PatternAfterIdent_Atom(
                                  PatternIdent_Name
                                )
                              ),
                              Type_Path(
                                "",
                                Type_Tail_End
                              ),
                              Expr_Call(
                                Expr_Field(
                                  Expr_IdentTail(
                                    "text",
                                    IdentTail_None
                                  ),
                                  "codepoint_at"
                                ),
                                Arg_Cons(
                                  Expr_Int(
                                    "0"
                                  ),
                                  Arg_End
                                )
                              )
                            ),
                            Stmt_Cons(
                              Stmt_Return(
                                Expr_IdentTail(
                                  "cp",
                                  IdentTail_None
                                )
                              ),
                              Stmt_End
                            )
                          )
                        )
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
