OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "patterns",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "patterns",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "value",
                Type_Path(
                  "Option",
                  Type_Tail_Generic(
                    TypeArg_Cons(
                      Type_Path(
                        "Point",
                        Type_Tail_End
                      ),
                      TypeArg_End
                    )
                  )
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_Expr(
                  Expr_Match(
                    Expr_MatchIdent(
                      "value",
                      MatchIdent_Name
                    ),
                    MatchArm_Cons(
                      MatchArm(
                        Pattern_IdentStart(
                          "whole",
                          PatternAfterIdent_Bind(
                            Pattern_IdentStart(
                              "Some",
                              PatternAfterIdent_Atom(
                                PatternIdent_Call(
                                  PatternList_Cons(
                                    Pattern_Record(
                                      PatternRecord_Cons(
                                        PatternRecordField(
                                          "x",
                                          Pattern_IdentStart(
                                            "",
                                            PatternAfterIdent_Atom(
                                              PatternIdent_Name
                                            )
                                          )
                                        ),
                                        PatternRecord_Cons(
                                          PatternRecordField(
                                            "y",
                                            Pattern_IdentStart(
                                              "inner",
                                              PatternAfterIdent_Bind(
                                                Pattern_IdentStart(
                                                  "Some",
                                                  PatternAfterIdent_Atom(
                                                    PatternIdent_Call(
                                                      PatternList_Cons(
                                                        Pattern_IdentStart(
                                                          "z",
                                                          PatternAfterIdent_Atom(
                                                            PatternIdent_Name
                                                          )
                                                        ),
                                                        PatternList_End
                                                      )
                                                    )
                                                  )
                                                )
                                              )
                                            )
                                          ),
                                          PatternRecord_End
                                        )
                                      )
                                    ),
                                    PatternList_End
                                  )
                                )
                              )
                            )
                          )
                        ),
                        MatchGuard_Some(
                          Expr_Binary(
                            OpGt,
                            Expr_IdentTail(
                              "z",
                              IdentTail_None
                            ),
                            Expr_Int(
                              "0"
                            )
                          )
                        ),
                        Expr_IdentTail(
                          "z",
                          IdentTail_None
                        )
                      ),
                      MatchArm_Cons(
                        MatchArm(
                          Pattern_IdentStart(
                            "Some",
                            PatternAfterIdent_Atom(
                              PatternIdent_Call(
                                PatternList_Cons(
                                  Pattern_Paren(
                                    Pattern_IdentStart(
                                      "a",
                                      PatternAfterIdent_Atom(
                                        PatternIdent_Name
                                      )
                                    ),
                                    PatternList_Cons(
                                      Pattern_IdentStart(
                                        "_",
                                        PatternAfterIdent_Atom(
                                          PatternIdent_Name
                                        )
                                      ),
                                      PatternList_End
                                    )
                                  ),
                                  PatternList_End
                                )
                              )
                            )
                          ),
                          MatchGuard_None,
                          Expr_IdentTail(
                            "a",
                            IdentTail_None
                          )
                        ),
                        MatchArm_Cons(
                          MatchArm(
                            Pattern_IdentStart(
                              "None",
                              PatternAfterIdent_Atom(
                                PatternIdent_Name
                              )
                            ),
                            MatchGuard_None,
                            Expr_Int(
                              "0"
                            )
                          ),
                          MatchArm_Cons(
                            MatchArm(
                              Pattern_Atom(
                                "ok"
                              ),
                              MatchGuard_None,
                              Expr_Int(
                                "1"
                              )
                            ),
                            MatchArm_Cons(
                              MatchArm(
                                Pattern_Int(
                                  "0"
                                ),
                                MatchGuard_None,
                                Expr_Int(
                                  "2"
                                )
                              ),
                              MatchArm_Cons(
                                MatchArm(
                                  Pattern_Bool(
                                    1
                                  ),
                                  MatchGuard_None,
                                  Expr_Int(
                                    "3"
                                  )
                                ),
                                MatchArm_Cons(
                                  MatchArm(
                                    Pattern_IdentStart(
                                      "_",
                                      PatternAfterIdent_Atom(
                                        PatternIdent_Name
                                      )
                                    ),
                                    MatchGuard_None,
                                    Expr_Int(
                                      "4"
                                    )
                                  ),
                                  MatchArm_End
                                )
                              )
                            )
                          )
                        )
                      )
                    )
                  )
                ),
                Stmt_End
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
