OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "letdestruct",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "destruct",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "point",
                Type_Path(
                  "Shape",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_Paren(
                    Pattern_IdentStart(
                      "x",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    PatternList_Cons(
                      Pattern_Paren(
                        Pattern_IdentStart(
                          "y",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        PatternList_Cons(
                          Pattern_IdentStart(
                            "z",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          PatternList_End
                        )
                      ),
                      PatternList_End
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Field(
                    Expr_IdentTail(
                      "point",
                      IdentTail_None
                    ),
                    "coords"
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_Record(
                      PatternRecord_Cons(
                        PatternRecordField(
                          "name",
                          Pattern_IdentStart(
                            "",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          )
                        ),
                        PatternRecord_Cons(
                          PatternRecordField(
                            "meta",
                            Pattern_Record(
                              PatternRecord_Cons(
                                PatternRecordField(
                                  "age",
                                  Pattern_IdentStart(
                                    "",
                                    PatternAfterIdent_Atom(
                                      PatternIdent_Name
                                    )
                                  )
                                ),
                                PatternRecord_Cons(
                                  PatternRecordField(
                                    "active",
                                    Pattern_IdentStart(
                                      "",
                                      PatternAfterIdent_Atom(
                                        PatternIdent_Name
                                      )
                                    )
                                  ),
                                  PatternRecord_End
                                )
                              )
                            )
                          ),
                          PatternRecord_End
                        )
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_IdentTail(
                      "point",
                      IdentTail_None
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "whole",
                        PatternAfterIdent_Bind(
                          Pattern_Record(
                            PatternRecord_Cons(
                              PatternRecordField(
                                "center",
                                Pattern_Record(
                                  PatternRecord_Cons(
                                    PatternRecordField(
                                      "x",
                                      Pattern_IdentStart(
                                        "cx",
                                        PatternAfterIdent_Atom(
                                          PatternIdent_Name
                                        )
                                      )
                                    ),
                                    PatternRecord_Cons(
                                      PatternRecordField(
                                        "y",
                                        Pattern_IdentStart(
                                          "cy",
                                          PatternAfterIdent_Atom(
                                            PatternIdent_Name
                                          )
                                        )
                                      ),
                                      PatternRecord_End
                                    )
                                  )
                                )
                              ),
                              PatternRecord_Cons(
                                PatternRecordField(
                                  "color",
                                  Pattern_IdentStart(
                                    "",
                                    PatternAfterIdent_Atom(
                                      PatternIdent_Name
                                    )
                                  )
                                ),
                                PatternRecord_End
                              )
                            )
                          )
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_IdentTail(
                        "point",
                        IdentTail_None
                      )
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "_",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_IdentTail(
                          "active",
                          IdentTail_None
                        )
                      ),
                      Stmt_Cons(
                        Stmt_Return(
                          Expr_Binary(
                            OpAdd,
                            Expr_Binary(
                              OpAdd,
                              Expr_Binary(
                                OpAdd,
                                Expr_Binary(
                                  OpAdd,
                                  Expr_Binary(
                                    OpAdd,
                                    Expr_IdentTail(
                                      "x",
                                      IdentTail_None
                                    ),
                                    Expr_IdentTail(
                                      "y",
                                      IdentTail_None
                                    )
                                  ),
                                  Expr_IdentTail(
                                    "z",
                                    IdentTail_None
                                  )
                                ),
                                Expr_IdentTail(
                                  "age",
                                  IdentTail_None
                                )
                              ),
                              Expr_IdentTail(
                                "cx",
                                IdentTail_None
                              )
                            ),
                            Expr_IdentTail(
                              "cy",
                              IdentTail_None
                            )
                          )
                        ),
                        Stmt_End
                      )
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
