OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "control",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "control",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "n",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_Expr(
                  Expr_If(
                    IfCond_Expr(
                      Expr_IfCondIdent(
                        "n",
                        IfCondIdent_Binary(
                          OpEqEq,
                          Expr_Int(
                            "0"
                          )
                        )
                      )
                    ),
                    Expr_Block(
                      Stmt_Cons(
                        Stmt_Return(
                          Expr_Int(
                            "0"
                          )
                        ),
                        Stmt_End
                      ),
                      TailExpr_None
                    ),
                    Expr_If(
                      IfCond_Let(
                        Pattern_IdentStart(
                          "Some",
                          PatternAfterIdent_Atom(
                            PatternIdent_Call(
                              PatternList_Cons(
                                Pattern_IdentStart(
                                  "x",
                                  PatternAfterIdent_Atom(
                                    PatternIdent_Name
                                  )
                                ),
                                PatternList_End
                              )
                            )
                          )
                        ),
                        Expr_Call(
                          Expr_Name(
                            "next"
                          ),
                          Arg_Cons(
                            Expr_IdentTail(
                              "n",
                              IdentTail_None
                            ),
                            Arg_End
                          )
                        )
                      ),
                      Expr_Block(
                        Stmt_Cons(
                          Stmt_Return(
                            Expr_IdentTail(
                              "x",
                              IdentTail_None
                            )
                          ),
                          Stmt_End
                        ),
                        TailExpr_None
                      ),
                      Expr_If(
                        IfCond_Expr(
                          Expr_IfCondIdent(
                            "n",
                            IfCondIdent_Binary(
                              OpLt,
                              Expr_Int(
                                "0"
                              )
                            )
                          )
                        ),
                        Expr_Block(
                          Stmt_Cons(
                            Stmt_Return(
                              Expr_Prefix(
                                Prefix_Neg,
                                Expr_IdentTail(
                                  "n",
                                  IdentTail_None
                                )
                              )
                            ),
                            Stmt_End
                          ),
                          TailExpr_None
                        ),
                        Expr_Block(
                          Stmt_Cons(
                            Stmt_For(
                              LoopLabel_Some,
                              Expr_Binary(
                                OpGt,
                                Expr_IdentTail(
                                  "n",
                                  IdentTail_None
                                ),
                                Expr_Int(
                                  "0"
                                )
                              ),
                              Expr_Block(
                                Stmt_Cons(
                                  Stmt_For(
                                    LoopLabel_None,
                                    Expr_Bool(
                                      1
                                    ),
                                    Expr_Block(
                                      Stmt_Cons(
                                        Stmt_Expr(
                                          Expr_If(
                                            IfCond_Expr(
                                              Expr_IfCondIdent(
                                                "done",
                                                IfCondIdent_Call(
                                                  Arg_End
                                                )
                                              )
                                            ),
                                            Expr_Block(
                                              Stmt_Cons(
                                                Stmt_Break(
                                                  LoopLabel_Some
                                                ),
                                                Stmt_End
                                              ),
                                              TailExpr_None
                                            ),
                                            Expr_Block(
                                              Stmt_Cons(
                                                Stmt_Continue(
                                                  LoopLabel_Some
                                                ),
                                                Stmt_End
                                              ),
                                              TailExpr_None
                                            )
                                          )
                                        ),
                                        Stmt_End
                                      ),
                                      TailExpr_None
                                    )
                                  ),
                                  Stmt_End
                                ),
                                TailExpr_None
                              )
                            ),
                            Stmt_End
                          ),
                          TailExpr_None
                        )
                      )
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_Return(
                    Expr_IdentTail(
                      "n",
                      IdentTail_None
                    )
                  ),
                  Stmt_End
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
