OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "control",
            Path_Cons(
              "resetshift",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "reset_shift",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "value",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Reset(
                    ControlLabel_Some,
                    Expr_Block(
                      Stmt_Cons(
                        Stmt_Expr(
                          Expr_Binary(
                            OpAdd,
                            Expr_Int(
                              "1"
                            ),
                            Expr_Shift(
                              ControlLabel_Some,
                              "k",
                              Expr_Block(
                                Stmt_Cons(
                                  Stmt_Expr(
                                    Expr_IdentTail(
                                      "k",
                                      IdentTail_Call(
                                        Arg_Cons(
                                          Expr_Int(
                                            "41"
                                          ),
                                          Arg_End
                                        ),
                                        IdentCallClosure_None
                                      )
                                    )
                                  ),
                                  Stmt_End
                                ),
                                TailExpr_None
                              )
                            )
                          )
                        ),
                        Stmt_End
                      ),
                      TailExpr_None
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "plain",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Reset(
                      ControlLabel_None,
                      Expr_Block(
                        Stmt_Cons(
                          Stmt_Expr(
                            Expr_Shift(
                              ControlLabel_None,
                              "cont",
                              Expr_Block(
                                Stmt_Cons(
                                  Stmt_Expr(
                                    Expr_IdentTail(
                                      "cont",
                                      IdentTail_Call(
                                        Arg_Cons(
                                          Expr_IdentTail(
                                            "value",
                                            IdentTail_None
                                          ),
                                          Arg_End
                                        ),
                                        IdentCallClosure_None
                                      )
                                    )
                                  ),
                                  Stmt_End
                                ),
                                TailExpr_None
                              )
                            )
                          ),
                          Stmt_End
                        ),
                        TailExpr_None
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_Return(
                      Expr_IdentTail(
                        "plain",
                        IdentTail_None
                      )
                    ),
                    Stmt_End
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
