OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "defs",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Type(
        TypeItem(
          "UserId",
          Type_Path(
            "i64",
            Type_Tail_End
          )
        )
      ),
      Item_Cons(
        Item_Adt(
          AdtItem(
            "Option",
            Generic_Cons(
              "T",
              Generic_End
            ),
            AdtVariant_Cons(
              AdtVariant(
                "Some",
                AdtVariantArg_Ident(
                  "T",
                  AdtVariantArg_Type(
                    Type_Tail_End,
                    TypeArg_End
                  )
                )
              ),
              AdtVariant_Cons(
                AdtVariant(
                  "None",
                  TypeArg_End
                ),
                AdtVariant_End
              )
            )
          )
        ),
        Item_Cons(
          Item_Union(
            UnionItem(
              "Bits",
              UnionField_Cons(
                UnionField(
                  "u32v",
                  Type_Path(
                    "u32",
                    Type_Tail_End
                  )
                ),
                UnionField_Cons(
                  UnionField(
                    "f32v",
                    Type_Path(
                      "f32",
                      Type_Tail_End
                    )
                  ),
                  UnionField_End
                )
              )
            )
          ),
          Item_Cons(
            Item_Def(
              DefItem2(
                "pi",
                DefConst(
                  Type_Path(
                    "f32",
                    Type_Tail_End
                  ),
                  Expr_Float(
                    "3.1415926"
                  )
                )
              )
            ),
            Item_Cons(
              Item_Def(
                DefItem2(
                  "helper",
                  DefFun(
                    Generic_End,
                    Param_Cons(
                      Param(
                        "x",
                        Type_Path(
                          "i64",
                          Type_Tail_End
                        )
                      ),
                      Param_End
                    ),
                    Type_Path(
                      "i64",
                      Type_Tail_End
                    ),
                    Expr_Block(
                      Stmt_Cons(
                        Stmt_Return(
                          Expr_Binary(
                            OpAdd,
                            Expr_IdentTail(
                              "x",
                              IdentTail_None
                            ),
                            Expr_Int(
                              "1"
                            )
                          )
                        ),
                        Stmt_End
                      ),
                      TailExpr_None
                    )
                  )
                )
              ),
              Item_Cons(
                Item_Def(
                  DefItem2(
                    "Vec2",
                    DefFun(
                      Generic_End,
                      Param_Cons(
                        Param(
                          "self",
                          Type_Path(
                            "",
                            Type_Tail_End
                          )
                        ),
                        Param_End
                      ),
                      Type_Path(
                        "f32",
                        Type_Tail_End
                      ),
                      Expr_Block(
                        Stmt_Cons(
                          Stmt_Return(
                            Expr_IdentTail(
                              "sqrt",
                              IdentTail_Call(
                                Arg_Cons(
                                  Expr_Binary(
                                    OpAdd,
                                    Expr_Binary(
                                      OpMul,
                                      Expr_Field(
                                        Expr_IdentTail(
                                          "self",
                                          IdentTail_None
                                        ),
                                        "x"
                                      ),
                                      Expr_Field(
                                        Expr_IdentTail(
                                          "self",
                                          IdentTail_None
                                        ),
                                        "x"
                                      )
                                    ),
                                    Expr_Binary(
                                      OpMul,
                                      Expr_Field(
                                        Expr_IdentTail(
                                          "self",
                                          IdentTail_None
                                        ),
                                        "y"
                                      ),
                                      Expr_Field(
                                        Expr_IdentTail(
                                          "self",
                                          IdentTail_None
                                        ),
                                        "y"
                                      )
                                    )
                                  ),
                                  Arg_End
                                ),
                                IdentCallClosure_None
                              )
                            )
                          ),
                          Stmt_End
                        ),
                        TailExpr_None
                      )
                    )
                  )
                ),
                Item_End
              )
            )
          )
        )
      )
    )
  )
)
