OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "lambda",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "closures",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "x",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "inc",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_ParenIdent(
                    "v",
                    ParenIdent_Lambda(
                      Type_Path(
                        "i64",
                        Type_Tail_End
                      ),
                      Param_End,
                      Expr_Binary(
                        OpAdd,
                        Expr_IdentTail(
                          "v",
                          IdentTail_None
                        ),
                        Expr_Int(
                          "1"
                        )
                      )
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "blocky",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Closure(
                      Param_End,
                      Expr_Block(
                        Stmt_Cons(
                          Stmt_LetPatternTyped(
                            Pattern_IdentStart(
                              "local",
                              PatternAfterIdent_Atom(
                                PatternIdent_Name
                              )
                            ),
                            Type_Path(
                              "",
                              Type_Tail_End
                            ),
                            Expr_Binary(
                              OpAdd,
                              Expr_IdentTail(
                                "x",
                                IdentTail_None
                              ),
                              Expr_Int(
                                "1"
                              )
                            )
                          ),
                          Stmt_Cons(
                            Stmt_Return(
                              Expr_IdentTail(
                                "local",
                                IdentTail_None
                              )
                            ),
                            Stmt_End
                          )
                        ),
                        TailExpr_None
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "pair",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_ParenIdent(
                        "a",
                        ParenIdent_Lambda(
                          Type_Path(
                            "i64",
                            Type_Tail_End
                          ),
                          Param_Cons(
                            Param(
                              "b",
                              Type_Path(
                                "i64",
                                Type_Tail_End
                              )
                            ),
                            Param_End
                          ),
                          Expr_Block(
                            Stmt_Cons(
                              Stmt_Return(
                                Expr_Binary(
                                  OpAdd,
                                  Expr_IdentTail(
                                    "a",
                                    IdentTail_None
                                  ),
                                  Expr_IdentTail(
                                    "b",
                                    IdentTail_None
                                  )
                                )
                              ),
                              Stmt_End
                            ),
                            TailExpr_None
                          )
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_Return(
                        Expr_Binary(
                          OpAdd,
                          Expr_IdentTail(
                            "inc",
                            IdentTail_Call(
                              Arg_Cons(
                                Expr_IdentTail(
                                  "blocky",
                                  IdentTail_Call(
                                    Arg_End,
                                    IdentCallClosure_None
                                  )
                                ),
                                Arg_End
                              ),
                              IdentCallClosure_None
                            )
                          ),
                          Expr_IdentTail(
                            "pair",
                            IdentTail_Call(
                              Arg_Cons(
                                Expr_Int(
                                  "1"
                                ),
                                Arg_Cons(
                                  Expr_Int(
                                    "2"
                                  ),
                                  Arg_End
                                )
                              ),
                              IdentCallClosure_None
                            )
                          )
                        )
                      ),
                      Stmt_End
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
