OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "memory",
            Path_Cons(
              "types",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "capabilities",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "p",
                Type_Path(
                  "Ptr",
                  Type_Tail_Generic(
                    TypeArg_Cons(
                      Type_Path(
                        "u8",
                        Type_Tail_End
                      ),
                      TypeArg_End
                    )
                  )
                )
              ),
              Param_Cons(
                Param(
                  "r",
                  Type_Path(
                    "Ref",
                    Type_Tail_Generic(
                      TypeArg_Cons(
                        Type_Path(
                          "i64",
                          Type_Tail_End
                        ),
                        TypeArg_End
                      )
                    )
                  )
                ),
                Param_Cons(
                  Param(
                    "u",
                    Type_Path(
                      "UnsafeRef",
                      Type_Tail_Generic(
                        TypeArg_Cons(
                          Type_Path(
                            "File",
                            Type_Tail_End
                          ),
                          TypeArg_End
                        )
                      )
                    )
                  ),
                  Param_End
                )
              )
            ),
            Type_Unit,
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "x",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Deref(
                    Expr_IdentTail(
                      "p",
                      IdentTail_None
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_Expr(
                    Expr_Assign(
                      Expr_IdentTail(
                        "r",
                        IdentTail_None
                      ),
                      Expr_Binary(
                        OpAdd,
                        Expr_Call(
                          Expr_Field(
                            Expr_IdentTail(
                              "r",
                              IdentTail_None
                            ),
                            "read"
                          ),
                          Arg_End
                        ),
                        Expr_Int(
                          "1"
                        )
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_Return(
                      Expr_Paren(
                        ExprList_End
                      )
                    ),
                    Stmt_End
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
