OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "paths",
            Path_Cons(
              "generics",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "generic_paths",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "xs",
                Type_Path(
                  "Vec",
                  Type_Tail_Generic(
                    TypeArg_Cons(
                      Type_Path(
                        "Option",
                        Type_Tail_Generic(
                          TypeArg_Cons(
                            Type_Path(
                              "Result",
                              Type_Tail_Generic(
                                TypeArg_Cons(
                                  Type_Path(
                                    "i64",
                                    Type_Tail_End
                                  ),
                                  TypeArg_Cons(
                                    Type_Atom(
                                      "error"
                                    ),
                                    TypeArg_End
                                  )
                                )
                              )
                            ),
                            TypeArg_End
                          )
                        )
                      ),
                      TypeArg_End
                    )
                  )
                )
              ),
              Param_End
            ),
            Type_Path(
              "Option",
              Type_Tail_Generic(
                TypeArg_Cons(
                  Type_Path(
                    "i64",
                    Type_Tail_End
                  ),
                  TypeArg_End
                )
              )
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "value",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Call(
                    Expr_Field(
                      Expr_IdentTail(
                        "Option",
                        IdentTail_None
                      ),
                      "Some"
                    ),
                    Arg_Cons(
                      Expr_Call(
                        Expr_Field(
                          Expr_IdentTail(
                            "Result",
                            IdentTail_None
                          ),
                          "Ok"
                        ),
                        Arg_Cons(
                          Expr_Int(
                            "1"
                          ),
                          Arg_End
                        )
                      ),
                      Arg_End
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_Return(
                    Expr_IdentTail(
                      "value",
                      IdentTail_None
                    )
                  ),
                  Stmt_End
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
