OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "attribute",
            Path_Cons(
              "targets",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "main",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i32",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "value",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Int(
                    "1"
                  )
                ),
                Stmt_Cons(
                  Stmt_Expr(
                    Expr_Unsafe(
                      Expr_Block(
                        Stmt_Cons(
                          Stmt_Expr(
                            Expr_IdentTail(
                              "use_low_level",
                              IdentTail_Call(
                                Arg_End,
                                IdentCallClosure_None
                              )
                            )
                          ),
                          Stmt_End
                        ),
                        TailExpr_None
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_Expr(
                      Expr_IdentTail(
                        "call",
                        IdentTail_Call(
                          Arg_Cons(
                            Expr_IdentTail(
                              "value",
                              IdentTail_None
                            ),
                            Arg_End
                          ),
                          IdentCallClosure_Some(
                            Expr_Closure(
                              Param_Cons(
                                Param(
                                  "x",
                                  Type_Path(
                                    "",
                                    Type_Tail_End
                                  )
                                ),
                                Param_End
                              ),
                              Expr_Block(
                                Stmt_Cons(
                                  Stmt_Expr(
                                    Expr_Binary(
                                      OpAdd,
                                      Expr_IdentTail(
                                        "x",
                                        IdentTail_None
                                      ),
                                      Expr_Int(
                                        "1"
                                      )
                                    )
                                  ),
                                  Stmt_End
                                ),
                                TailExpr_None
                              )
                            )
                          )
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_Return(
                        Expr_Int(
                          "0"
                        )
                      ),
                      Stmt_End
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
