OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "unicode",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "unicode_idents",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "🍋",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_Cons(
                Param(
                  "火",
                  Type_Path(
                    "i64",
                    Type_Tail_End
                  )
                ),
                Param_End
              )
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "测试一下语法容忍度",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Binary(
                    OpAdd,
                    Expr_IdentTail(
                      "🍋",
                      IdentTail_None
                    ),
                    Expr_IdentTail(
                      "火",
                      IdentTail_None
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "_🥲123",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_IdentTail(
                      "测试一下语法容忍度",
                      IdentTail_None
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "café",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_IdentTail(
                        "_🥲123",
                        IdentTail_None
                      )
                    ),
                    Stmt_Cons(
                      Stmt_Return(
                        Expr_IdentTail(
                          "café",
                          IdentTail_None
                        )
                      ),
                      Stmt_End
                    )
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
