OK(
  SourceFile(
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "everything",
            Path_Cons(
              "smoke",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Adt(
        AdtItem(
          "Smoke",
          Generic_Cons(
            "T",
            Generic_End
          ),
          AdtVariant_Cons(
            AdtVariant(
              "Smoke",
              AdtVariantArg_Ident(
                "value",
                AdtVariantArg_Field(
                  Type_Path(
                    "T",
                    Type_Tail_End
                  ),
                  AdtVariantField_Cons(
                    "tag",
                    Type_Atom(
                      "ok"
                    ),
                    AdtVariantField_End
                  )
                )
              )
            ),
            AdtVariant_End
          )
        )
      ),
      Item_Cons(
        Item_Def(
          DefItem2(
            "smoke",
            DefFun(
              Generic_Cons(
                "T",
                Generic_End
              ),
              Param_Cons(
                Param(
                  "input",
                  Type_Path(
                    "T",
                    Type_Tail_End
                  )
                ),
                Param_End
              ),
              Type_Path(
                "i64",
                Type_Tail_End
              ),
              Expr_Block(
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "record",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Record(
                      Record_First(
                        "input",
                        RecordTail_Shorthand(
                          RecordField_Cons(
                            RecordField(
                              "status",
                              Expr_Atom(
                                "ok"
                              )
                            ),
                            RecordField_End
                          )
                        )
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_LetPatternTyped(
                      Pattern_IdentStart(
                        "updated",
                        PatternAfterIdent_Atom(
                          PatternIdent_Name
                        )
                      ),
                      Type_Path(
                        "",
                        Type_Tail_End
                      ),
                      Expr_Record(
                        Record_First(
                          "record",
                          Record_Update(
                            Expr_Name(
                              ""
                            ),
                            RecordField_Cons(
                              RecordField(
                                "status",
                                Expr_Atom(
                                  "done"
                                )
                              ),
                              RecordField_End
                            )
                          )
                        )
                      )
                    ),
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "answer",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "",
                          Type_Tail_End
                        ),
                        Expr_Reset(
                          ControlLabel_None,
                          Expr_Block(
                            Stmt_Cons(
                              Stmt_Expr(
                                Expr_Match(
                                  Expr_MatchIdent(
                                    "Some",
                                    MatchIdent_Call(
                                      Arg_Cons(
                                        Expr_IdentTail(
                                          "updated",
                                          IdentTail_None
                                        ),
                                        Arg_End
                                      )
                                    )
                                  ),
                                  MatchArm_Cons(
                                    MatchArm(
                                      Pattern_IdentStart(
                                        "whole",
                                        PatternAfterIdent_Bind(
                                          Pattern_IdentStart(
                                            "Some",
                                            PatternAfterIdent_Atom(
                                              PatternIdent_Call(
                                                PatternList_Cons(
                                                  Pattern_IdentStart(
                                                    "v",
                                                    PatternAfterIdent_Atom(
                                                      PatternIdent_Name
                                                    )
                                                  ),
                                                  PatternList_End
                                                )
                                              )
                                            )
                                          )
                                        )
                                      ),
                                      MatchGuard_Some(
                                        Expr_Binary(
                                          OpEqEq,
                                          Expr_Field(
                                            Expr_IdentTail(
                                              "v",
                                              IdentTail_None
                                            ),
                                            "status"
                                          ),
                                          Expr_Atom(
                                            "done"
                                          )
                                        )
                                      ),
                                      Expr_Shift(
                                        ControlLabel_None,
                                        "k",
                                        Expr_Block(
                                          Stmt_Cons(
                                            Stmt_Expr(
                                              Expr_IdentTail(
                                                "k",
                                                IdentTail_Call(
                                                  Arg_Cons(
                                                    Expr_Int(
                                                      "42"
                                                    ),
                                                    Arg_End
                                                  ),
                                                  IdentCallClosure_None
                                                )
                                              )
                                            ),
                                            Stmt_End
                                          ),
                                          TailExpr_None
                                        )
                                      )
                                    ),
                                    MatchArm_Cons(
                                      MatchArm(
                                        Pattern_IdentStart(
                                          "None",
                                          PatternAfterIdent_Atom(
                                            PatternIdent_Name
                                          )
                                        ),
                                        MatchGuard_None,
                                        Expr_Int(
                                          "0"
                                        )
                                      ),
                                      MatchArm_Cons(
                                        MatchArm(
                                          Pattern_IdentStart(
                                            "_",
                                            PatternAfterIdent_Atom(
                                              PatternIdent_Name
                                            )
                                          ),
                                          MatchGuard_None,
                                          Expr_Int(
                                            "1"
                                          )
                                        ),
                                        MatchArm_End
                                      )
                                    )
                                  )
                                )
                              ),
                              Stmt_End
                            ),
                            TailExpr_None
                          )
                        )
                      ),
                      Stmt_Cons(
                        Stmt_Return(
                          Expr_Binary(
                            OpPipeGt,
                            Expr_IdentTail(
                              "answer",
                              IdentTail_None
                            ),
                            Expr_IdentTail(
                              "finish",
                              IdentTail_Call(
                                Arg_Cons(
                                  Expr_IdentTail(
                                    "_",
                                    IdentTail_None
                                  ),
                                  Arg_End
                                ),
                                IdentCallClosure_None
                              )
                            )
                          )
                        ),
                        Stmt_End
                      )
                    )
                  )
                ),
                TailExpr_None
              )
            )
          )
        ),
        Item_End
      )
    )
  )
)
